### ISSUE TITLE
setBackground in runtime

### ISSUE THREAD

**Issue by hardz** [gilvegliach/TransparentTextTextView#3]
Thanks Dear for Making this Awesome Textview.
It's work fine but i didn't figure out how to change BackgroundColor on touch events.

TansText.setBackgroundColor(Color.parseColor("#ffffff"));//it's work fine

but onTouch of otherview i have to make BackgroundColor semi transparent. How..?

Thanks in Advance...!

**Comment by gilvegliach** [comment]
Thanks a lot, feedback is really appreciated!

To solve you problem you can:
- Set a `View.OnTouchListener` on the over view
- From there call `TrasparentTextTextView.setBackgroundColor()` with a semitrasparent color.

Semitransparent background is supported, you can test it directly from the sample:
- comment out line 55 in the trasparent-text-textview/build.gradle (this is an open issue):
  
  //apply from: 'android-jcenter.gradle'
- change background from #e91e63 to #80e91e63 (50% alpha) in the sample
- build and launch the sample

**Comment by gilvegliach** [comment]
Could you check if release 1.0.2 fixes your problem?

**Comment by gilvegliach** [comment]
Fixed adding docs in commit 478761f.
