### ISSUE TITLE
Android setText not clear the previous one

### ISSUE THREAD

**Issue by samy-baili** [gilvegliach/TransparentTextTextView#4]
![screenshot_20160325-192337](https://cloud.githubusercontent.com/assets/11545612/14050978/eca1c828-f2bf-11e5-92e1-24c5b8713738.png)

**Comment by gilvegliach** [comment]
Fixed on master and to be released in 1.0.2. 

I would like to fix also the other bugs in the next release, so it might take a while to roll out. In the meantime you can get the source code from master and import it as a module like in the sample project. (that is with: compile project(':transparent-text-textview'))

**Comment by samy-baili** [comment]
Perfect Thank you Gil, Could you warning me when the 1.0.2 is available please ?

**Comment by gilvegliach** [comment]
Sure, no problem :)
