### ISSUE TITLE
Mask should be in ALPHA_8 format

### ISSUE THREAD

**Issue by paveldudka** [gilvegliach/TransparentTextTextView#6]
Mask bitmap itself uses only alpha channel. There is no need to create full color `ARGB_8888` bitmap for it. `Config.ALPHA_8` is enough for a mask which will consume 4 times less memory.

**Comment by gilvegliach** [comment]
Thanks for the report, it looks a good idea. I'll test as soon as I have some free time.

**Comment by gilvegliach** [comment]
Fixed on master.
